package com.kloc.unistore.entity.productVariation

data class ProductVariationItem(
//    val _links: Links?,
//    val attributes: List<Attribute?>?,
//    val backordered: Boolean?,
//    val backorders: String?,
//    val backorders_allowed: Boolean?,
//    val date_created: String?,
//    val date_created_gmt: String?,
//    val date_modified: String?,
//    val date_modified_gmt: String?,
//    val date_on_sale_from: Any?,
//    val date_on_sale_from_gmt: Any?,
//    val date_on_sale_to: Any?,
//    val date_on_sale_to_gmt: Any?,
//    val description: String?,
//    val dimensions: Dimensions?,
//    val download_expiry: Any?,
//    val download_limit: Any?,
//    val downloadable: Boolean?,
//    val downloads: List<Any?>?,
    val id: Int?,
//    val image: Any?,
//    val low_stock_amount: Any?,
//    val manage_stock: Boolean?,
//    val menu_order: Any?,
//    val meta_data: List<Any?>?,
    val name: String?,
//    val on_sale: Boolean?,
//    val parent_id: Any?,
//    val permalink: String?,
//    val price: Double?,
//    val purchasable: Boolean?,
    val regular_price: String,
//    val sale_price: Any?,
//    val shipping_class: String?,
//    val shipping_class_id: Any?,
//    val sku: String?,
//    val status: String?,
//    val stock_quantity: Any?,
//    val stock_status: String?,
//    val tax_class: String?,
//    val tax_status: String?,
//    val virtual: Boolean?,
//    val weight: String?
)